config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    collection do
      post 'register'
    end
  end

  root 'courses#index'

  resources :students do
    collection do
      post 'sign_up'
      get 'register'
      get 'login'
      post 'login'
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_students
	has_many :students,:through => :sourse_students
end

app/models/sourse_student.rb
class SourseStudent < ActiveRecord::Base
	belongs_to :student
	belongs_to :course
end

app/models/student.rb
class Student < ActiveRecord::Base
	attr_accessor :password
	has_many :course_students
	has_many :courses,:through => :course_students
	validates :email, presence: true,
			  format: {with: /[^\w.]+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$]/,on: :create },
			  #regexlib.com
			  uniqueness: true 
			  #:on => :update

	validates :password,:presence => {:message => 'khong the bo trong'},
						confirmation: true
	validates :enscripted_password, :presence => true, :on => :create
	before_validation :enscripted_password, :if => "password.present?" # lambda
	def enscript_password
		@enscripted_password = Digest::MD5.base64digest(self.password) #@password co the thay cho self.password--nhung @password qua them ham xu ly
																	 # def password 
																	 # 	@password + '..'
																	 # end
	end
	def enscript_password
      self.enscript_password = self.class.encode(password)
    end
  	def self.login_by_email_and_password(email, password) #class method,kiem tra ban than co login dc hay ko

      student = where(:email => email.first)
      password.present? && student.password == encode(password)# credential_params
  	end
  	def self.encode(text)
    	Digest::MD5.base64digest(text)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  def require_login
    if session[:email].nil?
    	redirect_to login_students_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:new,:show, :edit, :update, :destroy]

  def register
    @current_student = Student.find_by_email(sessionp[:logined_email])
    @courses = Course.where(:id => params[:course][:ids])
    @current_student.courses = courses
    if @current_student.save
      redirect_to student_path(@current_student)
    else
      redirect_to courses_path
    end
  end
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      if params[:id].nil?
        @course = Course.new()
      else
        @course = Course.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :start_at_date, :finish_at_date, :coach)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_login,:only =>[:register,:sign_up,:login]
  def index

  end
  def show
    @student = Student.find(params[:id])
    @course = @student.courses
    
  end

  def register
  	@student = Student.new #khoi tao bien student
  end

  def sign_up
  	@student = Student.new(student_params)
  	if @student.save
  		redirect_to '/students'
  	else
  		render :register
    end
  end
 

  def login
    if request.post?
      do_login
    else
      render :login
    end

  end

  private
  def do_login
      if Student.self.login_by_email_and_password(student_params)
        session[:logined_email] = params[:email]
        flash[:notice] = 'login success'
        redirect_to '/students'
      else
        redirect_to '/login'
      end
  end
  def student_params
     params.require(:student).permit(:email, :password)
    #{:email => 'asdas@asdsa.com', :password => 'asdsad'}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_at_date %><br>
    <%= f.date_select :start_at_date %>
  </div>
  <div class="field">
    <%= f.label :finish_at_date %><br>
    <%= f.date_select :finish_at_date %>
  </div>
  <div class="field">
    <%= f.label :coach %><br>
    <%= f.text_field :coach %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>
<% form_tag register_courses_path,:method => :post do |f|%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start at date</th>
      <th>Finish at date</th>
      <th>Coach</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= check_box_tag "courses[ids][]",course.id, 0,class: 'register-checkbox' %></td>

        <td><%= course.name %></td>
        <td><%= course.start_at_date %></td>
        <td><%= course.finish_at_date %></td>
        <td><%= course.coach %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%=submit_tag 'Register'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Start at date:</strong>
  <%= @course.start_at_date %>
</p>

<p>
  <strong>Finish at date:</strong>
  <%= @course.finish_at_date %>
</p>

<p>
  <strong>Coach:</strong>
  <%= @course.coach %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dangkykhoahoc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/students/login.html.erb
<%=form_for :student, :url => login_students_path, method: :post do |f|%>
	<%= f.label :email %>
	<%= f.email_field :email%>
	<%= f.label :password %>
	<%= f.password_field :password%>
	<%= f.submit "Login"%>
<% end %>

app/views/students/register.html.erb
<%=form_for :student, url: sign_up_students_path, method: :post do |f|%>
	<%= f.label :email %>
	<%= f.email_field :email%>
	<%= f.label :password %>
	<%= f.password_field :password%>
	<%= f.submit%>
<% end %>